version: "3"
services:
    app:
        build: .
        ports:
            - "8888:80"
        volumes:
            - .:/var/www/html
        links:
            - mariadb:mariadb
    mariadb:
        image: mariadb:10.4.4
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=myboard
            - MYSQL_ROOT_PASSWORD=password